clean again -- try it for real

diff --git a/.github/workflows/upgrade-one-python-dependency.yml b/.github/workflows/upgrade-one-python-dependency.yml
--- a/.github/workflows/upgrade-one-python-dependency.yml
+++ b/.github/workflows/upgrade-one-python-dependency.yml
@@ -36,16 +36,15 @@ jobs:
         env:
           PACKAGE: "${{ inputs.package }}"
         run: |
-          #make upgrade-package package="$PACKAGE"
-          echo do nothing TODO
+          make upgrade-package package="$PACKAGE"
 
-      # - name: PR preflight
-      #   run: |
-      #     # Fail early (and avoid quiet failure of create-pull-request action)
-      #     git diff --exit-code && {
-      #         echo "Error: No changes, so not creating PR." | tee -a $GITHUB_STEP_SUMMARY
-      #         exit 1
-      #     }
+      - name: PR preflight
+        run: |
+          # Fail early (and avoid quiet failure of create-pull-request action)
+          git diff --exit-code && {
+              echo "Error: No changes, so not creating PR." | tee -a "$GITHUB_STEP_SUMMARY"
+              exit 1
+          }
 
       - name: Make a PR
         id: make-pr
@@ -67,8 +66,8 @@ jobs:
           PR_URL: "${{ steps.make-pr.outputs.pull-request-url }}"
         run: |
           if [[ -z "$PR_URL" ]]; then
-              echo "PR not created; see log for more information" | tee -a $GITHUB_STEP_SUMMARY
+              echo "PR not created; see log for more information" | tee -a "$GITHUB_STEP_SUMMARY"
               exit 1
           else
-              echo "PR created or updated: $PR_URL" | tee -a $GITHUB_STEP_SUMMARY
+              echo "PR created or updated: $PR_URL" | tee -a "$GITHUB_STEP_SUMMARY"
           fi
